// Code generated by Kitex v0.10.1. DO NOT EDIT.

package helloservice

import (
	"context"
	"errors"
	hello "github.com/ZUCCzwp/ddd/my-awesome-service/kitex_gen/hello"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SayHello": kitex.NewMethodInfo(
		sayHelloHandler,
		newSayHelloArgs,
		newSayHelloResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	helloServiceServiceInfo                = NewServiceInfo()
	helloServiceServiceInfoForClient       = NewServiceInfoForClient()
	helloServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return helloServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return helloServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return helloServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "helloService"
	handlerType := (*hello.HelloService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.10.1",
		Extra:           extra,
	}
	return svcInfo
}

func sayHelloHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(hello.Request)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(hello.HelloService).SayHello(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SayHelloArgs:
		success, err := handler.(hello.HelloService).SayHello(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SayHelloResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSayHelloArgs() interface{} {
	return &SayHelloArgs{}
}

func newSayHelloResult() interface{} {
	return &SayHelloResult{}
}

type SayHelloArgs struct {
	Req *hello.Request
}

func (p *SayHelloArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(hello.Request)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SayHelloArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SayHelloArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SayHelloArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SayHelloArgs) Unmarshal(in []byte) error {
	msg := new(hello.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SayHelloArgs_Req_DEFAULT *hello.Request

func (p *SayHelloArgs) GetReq() *hello.Request {
	if !p.IsSetReq() {
		return SayHelloArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SayHelloArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SayHelloArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SayHelloResult struct {
	Success *hello.Response
}

var SayHelloResult_Success_DEFAULT *hello.Response

func (p *SayHelloResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(hello.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SayHelloResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SayHelloResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SayHelloResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SayHelloResult) Unmarshal(in []byte) error {
	msg := new(hello.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SayHelloResult) GetSuccess() *hello.Response {
	if !p.IsSetSuccess() {
		return SayHelloResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SayHelloResult) SetSuccess(x interface{}) {
	p.Success = x.(*hello.Response)
}

func (p *SayHelloResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SayHelloResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SayHello(ctx context.Context, Req *hello.Request) (r *hello.Response, err error) {
	var _args SayHelloArgs
	_args.Req = Req
	var _result SayHelloResult
	if err = p.c.Call(ctx, "SayHello", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
